# Generated by Django 4.0.5 on 2022-06-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200, verbose_name='Ime Lokacije')),
                ('adresa', models.CharField(max_length=200, verbose_name='Adressa')),
                ('tel', models.CharField(max_length=15, verbose_name='Broj Telefona')),
                ('web', models.URLField(blank=True, verbose_name='Web Adresa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Adresa')),
                ('owner', models.IntegerField(blank=True, default=1, verbose_name='Vlasnik Lokacije')),
            ],
        ),
        migrations.CreateModel(
            name='NightBirdUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='Mail Korisnika')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=120, verbose_name='Naziv Dešavanja')),
                ('event_date', models.DateTimeField(verbose_name='Datum Dogadjaja')),
                ('opis', models.TextField(blank=True)),
                ('gosti', models.ManyToManyField(blank=True, to='main.nightbirduser')),
                ('lokacija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
