# Generated by Django 4.0.5 on 2022-06-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='lokacija',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='location',
            name='adresa',
            field=models.CharField(max_length=200, verbose_name='Adresa'),
        ),
    ]
